site_name: GenShell
site_description: "Documentation for the GenShell POSIX shell and optional Qwen-based LLM sidecar."
site_url: ""
repo_url: ""
nav:
  - Home: index.md
  - Guides:
      - Build & Platform: guides/build.md
      - LLM Sidecar: guides/llm-sidecar.md
  - Development:
      - Practices: development/practices.md
  - Reference:
      - Repository Layout: reference/repo-layout.md
      - LLM Download Guide: reference/llm-download.md
      - API Reference: api/index.md
  - Contributing:
      - Contributor Guide: contributing/contributor-guide.md
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
plugins:
  - search
  - git-revision-date-localized:
      type: date
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - toc:
      permalink: true
  - smarty
  - sane_lists
  - def_list
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
extra:
  generator: false
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js
