GenShell: executor.h File Reference
executor.h File Reference
#include "../parser/ast.h"
#include "../shell.h"
Functions
int gs_execute_pipeline (struct gs_shell *shell, const gs_pipeline *pipeline)
Function Documentation
gs_execute_pipeline()
int gs_execute_pipeline (struct gs_shell * shell, const gs_pipeline * pipeline)
Definition at line 600 of file executor.c.
{
    if (!pipeline || pipeline->length == 0u) {
        return GS_OK;
    }
    if (pipeline->background) {
        fprintf(stderr, "genshell: background jobs are not implemented yet\n");
        shell->last_status = 1;
        return GS_ERR_UNIMPLEMENTED;
    }
    gs_prepared_command *prepared = (gs_prepared_command *)calloc(pipeline->length, sizeof(gs_prepared_command));
    if (!prepared) {
        return GS_ERR_ALLOC;
    }
    int rc = GS_OK;
    for (size_t i = 0; i < pipeline->length; ++i) {
        rc = prepare_command(shell, &pipeline->commands[i], &prepared[i]);
        if (rc != GS_OK) {
            goto done;
        }
    }
    int status = 0;
    if (pipeline->length == 1u && prepared[0].argc == 0u && prepared[0].redir_count > 0u) {
        status = execute_redir_only(&prepared[0]);
    } else if (pipeline->length == 1u && prepared[0].builtin && (prepared[0].builtin->flags & GS_BUILTIN_FLAG_PARENT)) {
        status = execute_parent_builtin(shell, &prepared[0]);
        if (status < 0) {
            status = 1;
        }
    } else {
        status = execute_pipeline_processes(shell, prepared, pipeline->length);
        if (status < 0) {
            status = 1;
        }
    }
    shell->last_status = status;
    rc = status;
done:
    for (size_t i = 0; i < pipeline->length; ++i) {
        dispose_prepared_command(&prepared[i]);
    }
    free(prepared);
    return rc;
}
References gs_pipeline::background, gs_pipeline::commands, dispose_prepared_command(), execute_parent_builtin(), execute_pipeline_processes(), execute_redir_only(), gs_builtin_spec::flags, GS_BUILTIN_FLAG_PARENT, GS_ERR_ALLOC, GS_ERR_UNIMPLEMENTED, GS_OK, gs_shell::last_status, gs_pipeline::length, and prepare_command().
Referenced by run_line().