GenShell: executor.c File Reference
executor.c File Reference
#include "executor.h"
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include "../builtins/builtin.h"
Functions
static void gs_strbuf_dispose (gs_strbuf *buf)
static int gs_strbuf_reserve (gs_strbuf *buf, size_t extra)
static int gs_strbuf_append_mem (gs_strbuf *buf, const char *data, size_t len)
static int gs_strbuf_append_char (gs_strbuf *buf, char ch)
static int gs_strbuf_append_int (gs_strbuf *buf, long value)
static int append_parameter (gs_strbuf *buf, const struct gs_shell *shell, const char *name, size_t len)
static int expand_word (const struct gs_shell *shell, const char *word, char **out_word)
static void dispose_expanded_redirs (gs_expanded_redir *redirs, size_t count)
static void dispose_prepared_command (gs_prepared_command *cmd)
static int prepare_command (struct gs_shell *shell, const gs_simple_command *command, gs_prepared_command *out)
static int open_redirection (const gs_expanded_redir *redir)
static int apply_child_redirs (const gs_expanded_redir *redirs, size_t count)
static int ensure_saved_descriptor (saved_descriptor **array, size_t *length, size_t *capacity, int fd)
static int apply_parent_redirs (const gs_expanded_redir *redirs, size_t count, saved_descriptor **out_saved, size_t *out_length)
static void restore_parent_redirs (saved_descriptor *saved, size_t count)
static int execute_parent_builtin (struct gs_shell *shell, gs_prepared_command *cmd)
static void execute_child_builtin (struct gs_shell *shell, gs_prepared_command *cmd)
static void execute_child_external (gs_prepared_command *cmd)
static int execute_pipeline_processes (struct gs_shell *shell, gs_prepared_command *cmds, size_t count)
static int execute_redir_only (gs_prepared_command *cmd)
int gs_execute_pipeline (struct gs_shell *shell, const gs_pipeline *pipeline)
Function Documentation
append_parameter()
int append_parameter (gs_strbuf * buf, const struct gs_shell * shell, const char * name, size_t len) static
Definition at line 101 of file executor.c.
{
    if (len == 0u) {
        return gs_strbuf_append_char(buf, '$');
    }
    if (len == 1u) {
        char tag = name[0];
        switch (tag) {
        case '?':
            return gs_strbuf_append_int(buf, shell ? shell->last_status : 0);
        case '$':
            return gs_strbuf_append_int(buf, (long)getpid());
        case '0': {
            const char *prog = (shell && shell->progname) ? shell->progname : "genshell";
            return gs_strbuf_append_mem(buf, prog, strlen(prog));
        }
        default:
            if (tag >= '1' && tag <= '9') {
                return GS_OK; /* positional params not yet implemented */
            }
            break;
        }
    }
    char *key = (char *)malloc(len + 1u);
    if (!key) {
        return GS_ERR_ALLOC;
    }
    memcpy(key, name, len);
    key[len] = '\0';
    const char *value = getenv(key);
    if (!value) {
        value = "";
    }
    int rc = gs_strbuf_append_mem(buf, value, strlen(value));
    free(key);
    return rc;
}
References GS_ERR_ALLOC, GS_OK, gs_strbuf_append_char(), gs_strbuf_append_int(), gs_strbuf_append_mem(), gs_shell::last_status, and gs_shell::progname.
Referenced by expand_word().
apply_child_redirs()
int apply_child_redirs (const gs_expanded_redir * redirs, size_t count) static
Definition at line 349 of file executor.c.
{
    for (size_t i = 0; i < count; ++i) {
        int fd = open_redirection(&redirs[i]);
        if (fd < 0) {
            fprintf(stderr, "genshell: failed to open %s: %s\n", redirs[i].target, strerror(errno));
            return GS_ERR_EXEC;
        }
        if (dup2(fd, redirs[i].fd) < 0) {
            fprintf(stderr, "genshell: redirection failed: %s\n", strerror(errno));
            close(fd);
            return GS_ERR_EXEC;
        }
        close(fd);
    }
    return GS_OK;
}
References GS_ERR_EXEC, GS_OK, and open_redirection().
Referenced by execute_child_builtin(), and execute_child_external().
apply_parent_redirs()
int apply_parent_redirs (const gs_expanded_redir * redirs, size_t count, saved_descriptor ** out_saved, size_t * out_length) static
Definition at line 391 of file executor.c.
{
    *out_saved = NULL;
    *out_length = 0u;
    if (count == 0u) {
        return GS_OK;
    }
    saved_descriptor *saved = NULL;
    size_t saved_len = 0u;
    size_t saved_cap = 0u;
    for (size_t i = 0; i < count; ++i) {
        int fd_index = ensure_saved_descriptor(&saved, &saved_len, &saved_cap, redirs[i].fd);
        if (fd_index < 0) {
            for (size_t j = 0; j < saved_len; ++j) {
                close(saved[j].saved_fd);
            }
            free(saved);
            return fd_index;
        }
        int fd = open_redirection(&redirs[i]);
        if (fd < 0) {
            fprintf(stderr, "genshell: failed to open %s: %s\n", redirs[i].target, strerror(errno));
            for (size_t j = 0; j < saved_len; ++j) {
                dup2(saved[j].saved_fd, saved[j].fd);
                close(saved[j].saved_fd);
            }
            free(saved);
            return GS_ERR_EXEC;
        }
        if (dup2(fd, redirs[i].fd) < 0) {
            fprintf(stderr, "genshell: redirection failed: %s\n", strerror(errno));
            close(fd);
            for (size_t j = 0; j < saved_len; ++j) {
                dup2(saved[j].saved_fd, saved[j].fd);
                close(saved[j].saved_fd);
            }
            free(saved);
            return GS_ERR_EXEC;
        }
        close(fd);
    }
    *out_saved = saved;
    *out_length = saved_len;
    return GS_OK;
}
References ensure_saved_descriptor(), GS_ERR_EXEC, GS_OK, and open_redirection().
Referenced by execute_parent_builtin(), and execute_redir_only().
dispose_expanded_redirs()
void dispose_expanded_redirs (gs_expanded_redir * redirs, size_t count) static
Definition at line 250 of file executor.c.
{
    if (!redirs) {
        return;
    }
    for (size_t i = 0; i < count; ++i) {
        free(redirs[i].target);
    }
    free(redirs);
}
Referenced by dispose_prepared_command().
dispose_prepared_command()
void dispose_prepared_command (gs_prepared_command * cmd) static
Definition at line 260 of file executor.c.
{
    if (!cmd) {
        return;
    }
    if (cmd->argv) {
        for (size_t i = 0; i < cmd->argc; ++i) {
            free(cmd->argv[i]);
        }
        free(cmd->argv);
    }
    dispose_expanded_redirs(cmd->redirs, cmd->redir_count);
    cmd->argv = NULL;
    cmd->argc = 0u;
    cmd->redirs = NULL;
    cmd->redir_count = 0u;
    cmd->builtin = NULL;
}
References dispose_expanded_redirs().
Referenced by gs_execute_pipeline(), and prepare_command().
ensure_saved_descriptor()
int ensure_saved_descriptor (saved_descriptor ** array, size_t * length, size_t * capacity, int fd) static
Definition at line 366 of file executor.c.
{
    for (size_t i = 0; i < *length; ++i) {
        if ((*array)[i].fd == fd) {
            return (int)i;
        }
    }
    if (*length + 1u > *capacity) {
        size_t new_cap = *capacity ? *capacity * 2u : 4u;
        saved_descriptor *tmp = (saved_descriptor *)realloc(*array, new_cap * sizeof(saved_descriptor));
        if (!tmp) {
            return GS_ERR_ALLOC;
        }
        *array = tmp;
        *capacity = new_cap;
    }
    int dup_fd = dup(fd);
    if (dup_fd < 0) {
        return GS_ERR_EXEC;
    }
    (*array)[*length].fd = fd;
    (*array)[*length].saved_fd = dup_fd;
    (*length)++;
    return (int)(*length - 1u);
}
References GS_ERR_ALLOC, and GS_ERR_EXEC.
Referenced by apply_parent_redirs().
execute_child_builtin()
void execute_child_builtin (struct gs_shell * shell, gs_prepared_command * cmd) static
Definition at line 466 of file executor.c.
{
    int rc = apply_child_redirs(cmd->redirs, cmd->redir_count);
    if (rc != GS_OK) {
        _exit(1);
    }
    int status = cmd->builtin->fn(shell, (int)cmd->argc, cmd->argv);
    if (status < 0) {
        status = 1;
    }
    _exit(status & 0xFF);
}
References apply_child_redirs(), gs_builtin_spec::fn, and GS_OK.
Referenced by execute_pipeline_processes().
execute_child_external()
void execute_child_external (gs_prepared_command * cmd) static
Definition at line 478 of file executor.c.
{
    int rc = apply_child_redirs(cmd->redirs, cmd->redir_count);
    if (rc != GS_OK) {
        _exit(1);
    }
    execvp(cmd->argv[0], cmd->argv);
    int code = (errno == ENOENT) ? 127 : 126;
    fprintf(stderr, "genshell: %s: %s\n", cmd->argv[0], strerror(errno));
    _exit(code);
}
References apply_child_redirs(), and GS_OK.
Referenced by execute_pipeline_processes().
execute_parent_builtin()
int execute_parent_builtin (struct gs_shell * shell, gs_prepared_command * cmd) static
Definition at line 452 of file executor.c.
{
    saved_descriptor *saved = NULL;
    size_t saved_len = 0u;
    int rc = apply_parent_redirs(cmd->redirs, cmd->redir_count, &saved, &saved_len);
    if (rc != GS_OK) {
        restore_parent_redirs(saved, saved_len);
        return rc;
    }
    int status = cmd->builtin->fn(shell, (int)cmd->argc, cmd->argv);
    restore_parent_redirs(saved, saved_len);
    return status;
}
References apply_parent_redirs(), gs_builtin_spec::fn, GS_OK, and restore_parent_redirs().
Referenced by gs_execute_pipeline().
execute_pipeline_processes()
int execute_pipeline_processes (struct gs_shell * shell, gs_prepared_command * cmds, size_t count) static
Definition at line 489 of file executor.c.
{
    pid_t *pids = (pid_t *)calloc(count, sizeof(pid_t));
    if (!pids) {
        return GS_ERR_ALLOC;
    }
    int prev_read = -1;
    int status_result = 0;
    for (size_t i = 0; i < count; ++i) {
        int pipefd[2] = {-1, -1};
        if (i + 1 < count) {
            if (pipe(pipefd) < 0) {
                fprintf(stderr, "genshell: pipe failed: %s\n", strerror(errno));
                if (prev_read >= 0) {
                    close(prev_read);
                    prev_read = -1;
                }
                status_result = GS_ERR_EXEC;
                goto cleanup;
            }
        }
        pid_t pid = fork();
        if (pid < 0) {
            fprintf(stderr, "genshell: fork failed: %s\n", strerror(errno));
            if (pipefd[0] >= 0) {
                close(pipefd[0]);
                close(pipefd[1]);
            }
            if (prev_read >= 0) {
                close(prev_read);
                prev_read = -1;
            }
            status_result = GS_ERR_EXEC;
            goto cleanup;
        }
        if (pid == 0) {
            if (prev_read >= 0 && dup2(prev_read, STDIN_FILENO) < 0) {
                fprintf(stderr, "genshell: dup2 failed: %s\n", strerror(errno));
                _exit(1);
            }
            if (pipefd[1] >= 0 && dup2(pipefd[1], STDOUT_FILENO) < 0) {
                fprintf(stderr, "genshell: dup2 failed: %s\n", strerror(errno));
                _exit(1);
            }
            if (pipefd[0] >= 0) {
                close(pipefd[0]);
            }
            if (pipefd[1] >= 0) {
                close(pipefd[1]);
            }
            if (prev_read >= 0) {
                close(prev_read);
            }
            if (cmds[i].builtin) {
                execute_child_builtin(shell, &cmds[i]);
            } else {
                execute_child_external(&cmds[i]);
            }
            _exit(1); /* should not reach */
        }
        pids[i] = pid;
        if (prev_read >= 0) {
            close(prev_read);
        }
        if (pipefd[1] >= 0) {
            close(pipefd[1]);
        }
        prev_read = pipefd[0];
    }
    if (prev_read >= 0) {
        close(prev_read);
    }
    for (size_t i = 0; i < count; ++i) {
        int wstatus = 0;
        if (waitpid(pids[i], &wstatus, 0) < 0) {
            status_result = GS_ERR_EXEC;
            continue;
        }
        if (i == count - 1) {
            if (WIFEXITED(wstatus)) {
                status_result = WEXITSTATUS(wstatus);
            } else if (WIFSIGNALED(wstatus)) {
                status_result = 128 + WTERMSIG(wstatus);
            }
        }
    }
cleanup:
    free(pids);
    return status_result;
}
References execute_child_builtin(), execute_child_external(), GS_ERR_ALLOC, and GS_ERR_EXEC.
Referenced by gs_execute_pipeline().
execute_redir_only()
int execute_redir_only (gs_prepared_command * cmd) static
Definition at line 589 of file executor.c.
{
    saved_descriptor *saved = NULL;
    size_t saved_len = 0u;
    int rc = apply_parent_redirs(cmd->redirs, cmd->redir_count, &saved, &saved_len);
    restore_parent_redirs(saved, saved_len);
    if (rc != GS_OK) {
        return 1;
    }
    return 0;
}
References apply_parent_redirs(), GS_OK, and restore_parent_redirs().
Referenced by gs_execute_pipeline().
expand_word()
int expand_word (const struct gs_shell * shell, const char * word, char ** out_word) static
Definition at line 138 of file executor.c.
{
    gs_strbuf buf = {0};
    const char *p = word;
    bool literal_next = false;
    while (p && *p) {
        char ch = *p++;
        if (literal_next) {
            int rc = gs_strbuf_append_char(&buf, ch);
            if (rc != GS_OK) {
                gs_strbuf_dispose(&buf);
                return rc;
            }
            literal_next = false;
            continue;
        }
        if (ch == GS_LITERAL_SENTINEL) {
            literal_next = true;
            continue;
        }
        if (ch == '~' && buf.length == 0u) {
            const char *home = getenv("HOME");
            if (!home) {
                home = "";
            }
            int rc = gs_strbuf_append_mem(&buf, home, strlen(home));
            if (rc != GS_OK) {
                gs_strbuf_dispose(&buf);
                return rc;
            }
            continue;
        }
        if (ch == '$') {
            if (!*p) {
                int rc = gs_strbuf_append_char(&buf, '$');
                if (rc != GS_OK) {
                    gs_strbuf_dispose(&buf);
                    return rc;
                }
                break;
            }
            if (*p == '$' || *p == '?' || *p == '0') {
                char special = *p++;
                int rc = append_parameter(&buf, shell, &special, 1u);
                if (rc != GS_OK) {
                    gs_strbuf_dispose(&buf);
                    return rc;
                }
                continue;
            }
            if (*p == '{') {
                ++p;
                const char *start = p;
                while (*p && *p != '}') {
                    ++p;
                }
                if (*p != '}') {
                    int rc = gs_strbuf_append_char(&buf, '$');
                    if (rc != GS_OK) {
                        gs_strbuf_dispose(&buf);
                        return rc;
                    }
                    p = start - 1;
                    continue;
                }
                size_t len = (size_t)(p - start);
                int rc = append_parameter(&buf, shell, start, len);
                if (rc != GS_OK) {
                    gs_strbuf_dispose(&buf);
                    return rc;
                }
                ++p; /* skip closing brace */
                continue;
            }
            if (isalnum((unsigned char)*p) || *p == '_') {
                const char *start = p;
                while (isalnum((unsigned char)*p) || *p == '_') {
                    ++p;
                }
                size_t len = (size_t)(p - start);
                int rc = append_parameter(&buf, shell, start, len);
                if (rc != GS_OK) {
                    gs_strbuf_dispose(&buf);
                    return rc;
                }
                continue;
            }
            int rc = gs_strbuf_append_char(&buf, '$');
            if (rc != GS_OK) {
                gs_strbuf_dispose(&buf);
                return rc;
            }
            continue;
        }
        int rc = gs_strbuf_append_char(&buf, ch);
        if (rc != GS_OK) {
            gs_strbuf_dispose(&buf);
            return rc;
        }
    }
    if (!buf.data) {
        buf.data = (char *)malloc(1u);
        if (!buf.data) {
            return GS_ERR_ALLOC;
        }
        buf.data[0] = '\0';
    }
    *out_word = buf.data;
    return GS_OK;
}
References append_parameter(), GS_ERR_ALLOC, GS_LITERAL_SENTINEL, GS_OK, gs_strbuf_append_char(), gs_strbuf_append_mem(), and gs_strbuf_dispose().
Referenced by prepare_command().
gs_execute_pipeline()
int gs_execute_pipeline (struct gs_shell * shell, const gs_pipeline * pipeline)
Definition at line 600 of file executor.c.
{
    if (!pipeline || pipeline->length == 0u) {
        return GS_OK;
    }
    if (pipeline->background) {
        fprintf(stderr, "genshell: background jobs are not implemented yet\n");
        shell->last_status = 1;
        return GS_ERR_UNIMPLEMENTED;
    }
    gs_prepared_command *prepared = (gs_prepared_command *)calloc(pipeline->length, sizeof(gs_prepared_command));
    if (!prepared) {
        return GS_ERR_ALLOC;
    }
    int rc = GS_OK;
    for (size_t i = 0; i < pipeline->length; ++i) {
        rc = prepare_command(shell, &pipeline->commands[i], &prepared[i]);
        if (rc != GS_OK) {
            goto done;
        }
    }
    int status = 0;
    if (pipeline->length == 1u && prepared[0].argc == 0u && prepared[0].redir_count > 0u) {
        status = execute_redir_only(&prepared[0]);
    } else if (pipeline->length == 1u && prepared[0].builtin && (prepared[0].builtin->flags & GS_BUILTIN_FLAG_PARENT)) {
        status = execute_parent_builtin(shell, &prepared[0]);
        if (status < 0) {
            status = 1;
        }
    } else {
        status = execute_pipeline_processes(shell, prepared, pipeline->length);
        if (status < 0) {
            status = 1;
        }
    }
    shell->last_status = status;
    rc = status;
done:
    for (size_t i = 0; i < pipeline->length; ++i) {
        dispose_prepared_command(&prepared[i]);
    }
    free(prepared);
    return rc;
}
References gs_pipeline::background, gs_pipeline::commands, dispose_prepared_command(), execute_parent_builtin(), execute_pipeline_processes(), execute_redir_only(), gs_builtin_spec::flags, GS_BUILTIN_FLAG_PARENT, GS_ERR_ALLOC, GS_ERR_UNIMPLEMENTED, GS_OK, gs_shell::last_status, gs_pipeline::length, and prepare_command().
Referenced by run_line().
gs_strbuf_append_char()
int gs_strbuf_append_char (gs_strbuf * buf, char ch) static
Definition at line 82 of file executor.c.
{
    int rc = gs_strbuf_reserve(buf, 1u);
    if (rc != GS_OK) {
        return rc;
    }
    buf->data[buf->length++] = ch;
    buf->data[buf->length] = '\0';
    return GS_OK;
}
References GS_OK, and gs_strbuf_reserve().
Referenced by append_parameter(), and expand_word().
gs_strbuf_append_int()
int gs_strbuf_append_int (gs_strbuf * buf, long value) static
Definition at line 92 of file executor.c.
{
    char tmp[32];
    int len = snprintf(tmp, sizeof(tmp), "%ld", value);
    if (len < 0) {
        return GS_ERR_EXEC;
    }
    return gs_strbuf_append_mem(buf, tmp, (size_t)len);
}
References GS_ERR_EXEC, and gs_strbuf_append_mem().
Referenced by append_parameter().
gs_strbuf_append_mem()
int gs_strbuf_append_mem (gs_strbuf * buf, const char * data, size_t len) static
Definition at line 68 of file executor.c.
{
    if (len == 0u) {
        return GS_OK;
    }
    int rc = gs_strbuf_reserve(buf, len);
    if (rc != GS_OK) {
        return rc;
    }
    memcpy(buf->data + buf->length, data, len);
    buf->length += len;
    buf->data[buf->length] = '\0';
    return GS_OK;
}
References GS_OK, and gs_strbuf_reserve().
Referenced by append_parameter(), expand_word(), and gs_strbuf_append_int().
gs_strbuf_dispose()
void gs_strbuf_dispose (gs_strbuf * buf) static
Definition at line 43 of file executor.c.
{
    free(buf->data);
    buf->data = NULL;
    buf->length = 0u;
    buf->capacity = 0u;
}
Referenced by expand_word().
gs_strbuf_reserve()
int gs_strbuf_reserve (gs_strbuf * buf, size_t extra) static
Definition at line 50 of file executor.c.
{
    size_t needed = buf->length + extra + 1u;
    if (buf->capacity >= needed) {
        return GS_OK;
    }
    size_t new_cap = buf->capacity ? buf->capacity : 32u;
    while (new_cap < needed) {
        new_cap *= 2u;
    }
    char *tmp = (char *)realloc(buf->data, new_cap);
    if (!tmp) {
        return GS_ERR_ALLOC;
    }
    buf->data = tmp;
    buf->capacity = new_cap;
    return GS_OK;
}
References GS_ERR_ALLOC, and GS_OK.
Referenced by gs_strbuf_append_char(), and gs_strbuf_append_mem().
open_redirection()
int open_redirection (const gs_expanded_redir * redir) static
Definition at line 324 of file executor.c.
{
    int flags = 0;
    mode_t mode = 0666;
    switch (redir->type) {
    case GS_REDIR_STDIN:
        flags = O_RDONLY;
        break;
    case GS_REDIR_STDOUT:
        flags = O_WRONLY | O_CREAT | O_TRUNC;
        break;
    case GS_REDIR_STDOUT_APPEND:
        flags = O_WRONLY | O_CREAT | O_APPEND;
        break;
    case GS_REDIR_STDERR:
        flags = O_WRONLY | O_CREAT | O_TRUNC;
        break;
    default:
        return -1;
    }
    int fd = open(redir->target, flags, mode);
    return fd;
}
References GS_REDIR_STDERR, GS_REDIR_STDIN, GS_REDIR_STDOUT, and GS_REDIR_STDOUT_APPEND.
Referenced by apply_child_redirs(), and apply_parent_redirs().
prepare_command()
int prepare_command (struct gs_shell * shell, const gs_simple_command * command, gs_prepared_command * out) static
Definition at line 278 of file executor.c.
{
    memset(out, 0, sizeof(*out));
    size_t argv_len = command->argc;
    out->argv = (char **)calloc(argv_len + 1u, sizeof(char *));
    if (!out->argv) {
        return GS_ERR_ALLOC;
    }
    for (size_t i = 0; i < command->argc; ++i) {
        char *expanded = NULL;
        int rc = expand_word(shell, command->argv[i], &expanded);
        if (rc != GS_OK) {
            dispose_prepared_command(out);
            return rc;
        }
        out->argv[i] = expanded;
    }
    out->argc = command->argc;
    out->argv[argv_len] = NULL;
    if (command->redir_count > 0u) {
        out->redirs = (gs_expanded_redir *)calloc(command->redir_count, sizeof(gs_expanded_redir));
        if (!out->redirs) {
            dispose_prepared_command(out);
            return GS_ERR_ALLOC;
        }
        out->redir_count = command->redir_count;
        for (size_t i = 0; i < command->redir_count; ++i) {
            char *expanded = NULL;
            int rc = expand_word(shell, command->redirs[i].target, &expanded);
            if (rc != GS_OK) {
                dispose_prepared_command(out);
                return rc;
            }
            out->redirs[i].type = command->redirs[i].type;
            out->redirs[i].fd = command->redirs[i].fd;
            out->redirs[i].target = expanded;
        }
    }
    const char *name = (out->argc > 0u) ? out->argv[0] : NULL;
    out->builtin = name ? gs_builtin_lookup(name) : NULL;
    return GS_OK;
}
References gs_simple_command::argc, gs_simple_command::argv, dispose_prepared_command(), expand_word(), gs_redirection::fd, gs_builtin_lookup(), GS_ERR_ALLOC, GS_OK, gs_simple_command::redir_count, gs_simple_command::redirs, gs_redirection::target, and gs_redirection::type.
Referenced by gs_execute_pipeline().
restore_parent_redirs()
void restore_parent_redirs (saved_descriptor * saved, size_t count) static
Definition at line 440 of file executor.c.
{
    if (!saved) {
        return;
    }
    for (size_t i = count; i > 0; --i) {
        size_t idx = i - 1;
        dup2(saved[idx].saved_fd, saved[idx].fd);
        close(saved[idx].saved_fd);
    }
    free(saved);
}
Referenced by execute_parent_builtin(), and execute_redir_only().