GenShell: parser.h File Reference
parser.h File Reference
#include "ast.h"
#include "lexer.h"
Functions
int gs_parse_tokens (const gs_token_buffer *tokens, gs_pipeline *out_pipeline)
Function Documentation
gs_parse_tokens()
int gs_parse_tokens (const gs_token_buffer * tokens, gs_pipeline * out_pipeline)
Definition at line 279 of file parser.c.
{
    memset(out_pipeline, 0, sizeof(*out_pipeline));
    parse_state st = {tokens, 0};
    command_vec commands = {0};
    int rc;
    while (true) {
        gs_simple_command cmd;
        rc = parse_simple_command(&st, &cmd);
        if (rc != GS_OK) {
            command_vec_dispose(&commands);
            return rc;
        }
        rc = command_vec_push(&commands, &cmd);
        if (rc != GS_OK) {
            for (size_t i = 0; i < cmd.argc; ++i) {
                free(cmd.argv[i]);
            }
            free(cmd.argv);
            for (size_t i = 0; i < cmd.redir_count; ++i) {
                free(cmd.redirs[i].target);
            }
            free(cmd.redirs);
            command_vec_dispose(&commands);
            return rc;
        }
        const gs_token *next = peek(&st);
        if (!next) {
            command_vec_dispose(&commands);
            return GS_ERR_PARSE;
        }
        if (next->type == GS_TOKEN_PIPE) {
            (void)consume(&st);
            continue;
        }
        if (next->type == GS_TOKEN_BACKGROUND) {
            out_pipeline->background = true;
            (void)consume(&st);
        }
        if (next->type == GS_TOKEN_SEMICOLON) {
            out_pipeline->terminator = true;
            (void)consume(&st);
        }
        break;
    }
    const gs_token *terminal = peek(&st);
    if (!terminal || terminal->type != GS_TOKEN_END) {
        command_vec_dispose(&commands);
        return GS_ERR_PARSE;
    }
    out_pipeline->commands = commands.items;
    out_pipeline->length = commands.length;
    return GS_OK;
}
References gs_simple_command::argc, gs_simple_command::argv, gs_pipeline::background, command_vec_dispose(), command_vec_push(), gs_pipeline::commands, consume(), GS_ERR_PARSE, GS_OK, GS_TOKEN_BACKGROUND, GS_TOKEN_END, GS_TOKEN_PIPE, GS_TOKEN_SEMICOLON, gs_pipeline::length, parse_simple_command(), peek(), gs_simple_command::redir_count, gs_simple_command::redirs, gs_redirection::target, gs_pipeline::terminator, and gs_token::type.
Referenced by run_line().