GenShell: parser.c File Reference
parser.c File Reference
#include "parser.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
Functions
static const gs_token * peek (const parse_state *st)
static const gs_token * consume (parse_state *st)
static void string_vec_dispose (string_vec *vec)
static int string_vec_push (string_vec *vec, char *value)
static void redir_vec_dispose (redir_vec *vec)
static int redir_vec_push (redir_vec *vec, const gs_redirection *redir)
static void command_vec_dispose (command_vec *vec)
static int command_vec_push (command_vec *vec, const gs_simple_command *cmd)
static int parse_io_number (const char *text, int *out_fd)
static int parse_redirection (parse_state *st, gs_redirection_type type, int default_fd, int explicit_fd, gs_redirection *out_redir)
static int parse_simple_command (parse_state *st, gs_simple_command *out_cmd)
int gs_parse_tokens (const gs_token_buffer *tokens, gs_pipeline *out_pipeline)
void gs_pipeline_dispose (gs_pipeline *pipeline)
Function Documentation
command_vec_dispose()
void command_vec_dispose (command_vec * vec) static
Definition at line 100 of file parser.c.
{
    if (!vec) {
        return;
    }
    for (size_t i = 0; i < vec->length; ++i) {
        gs_simple_command *cmd = &vec->items[i];
        for (size_t j = 0; j < cmd->argc; ++j) {
            free(cmd->argv[j]);
        }
        free(cmd->argv);
        for (size_t j = 0; j < cmd->redir_count; ++j) {
            free(cmd->redirs[j].target);
        }
        free(cmd->redirs);
    }
    free(vec->items);
    vec->items = NULL;
    vec->length = 0u;
    vec->capacity = 0u;
}
References gs_simple_command::argc, gs_simple_command::argv, gs_simple_command::redir_count, gs_simple_command::redirs, and gs_redirection::target.
Referenced by gs_parse_tokens().
command_vec_push()
int command_vec_push (command_vec * vec, const gs_simple_command * cmd) static
Definition at line 121 of file parser.c.
{
    if (vec->length + 1u > vec->capacity) {
        size_t new_cap = vec->capacity ? vec->capacity * 2u : 2u;
        gs_simple_command *tmp = (gs_simple_command *)realloc(vec->items, new_cap * sizeof(gs_simple_command));
        if (!tmp) {
            return GS_ERR_ALLOC;
        }
        vec->items = tmp;
        vec->capacity = new_cap;
    }
    vec->items[vec->length++] = *cmd;
    return GS_OK;
}
References GS_ERR_ALLOC, and GS_OK.
Referenced by gs_parse_tokens().
consume()
const gs_token * consume (parse_state * st) static
Definition at line 19 of file parser.c.
{
    const gs_token *token = peek(st);
    if (!token) {
        return NULL;
    }
    st->index++;
    return token;
}
References peek().
Referenced by gs_parse_tokens(), parse_redirection(), and parse_simple_command().
gs_parse_tokens()
int gs_parse_tokens (const gs_token_buffer * tokens, gs_pipeline * out_pipeline)
Definition at line 279 of file parser.c.
{
    memset(out_pipeline, 0, sizeof(*out_pipeline));
    parse_state st = {tokens, 0};
    command_vec commands = {0};
    int rc;
    while (true) {
        gs_simple_command cmd;
        rc = parse_simple_command(&st, &cmd);
        if (rc != GS_OK) {
            command_vec_dispose(&commands);
            return rc;
        }
        rc = command_vec_push(&commands, &cmd);
        if (rc != GS_OK) {
            for (size_t i = 0; i < cmd.argc; ++i) {
                free(cmd.argv[i]);
            }
            free(cmd.argv);
            for (size_t i = 0; i < cmd.redir_count; ++i) {
                free(cmd.redirs[i].target);
            }
            free(cmd.redirs);
            command_vec_dispose(&commands);
            return rc;
        }
        const gs_token *next = peek(&st);
        if (!next) {
            command_vec_dispose(&commands);
            return GS_ERR_PARSE;
        }
        if (next->type == GS_TOKEN_PIPE) {
            (void)consume(&st);
            continue;
        }
        if (next->type == GS_TOKEN_BACKGROUND) {
            out_pipeline->background = true;
            (void)consume(&st);
        }
        if (next->type == GS_TOKEN_SEMICOLON) {
            out_pipeline->terminator = true;
            (void)consume(&st);
        }
        break;
    }
    const gs_token *terminal = peek(&st);
    if (!terminal || terminal->type != GS_TOKEN_END) {
        command_vec_dispose(&commands);
        return GS_ERR_PARSE;
    }
    out_pipeline->commands = commands.items;
    out_pipeline->length = commands.length;
    return GS_OK;
}
References gs_simple_command::argc, gs_simple_command::argv, gs_pipeline::background, command_vec_dispose(), command_vec_push(), gs_pipeline::commands, consume(), GS_ERR_PARSE, GS_OK, GS_TOKEN_BACKGROUND, GS_TOKEN_END, GS_TOKEN_PIPE, GS_TOKEN_SEMICOLON, gs_pipeline::length, parse_simple_command(), peek(), gs_simple_command::redir_count, gs_simple_command::redirs, gs_redirection::target, gs_pipeline::terminator, and gs_token::type.
Referenced by run_line().
gs_pipeline_dispose()
void gs_pipeline_dispose (gs_pipeline * pipeline)
Definition at line 337 of file parser.c.
{
    if (!pipeline || !pipeline->commands) {
        return;
    }
    for (size_t i = 0; i < pipeline->length; ++i) {
        gs_simple_command *cmd = &pipeline->commands[i];
        if (cmd->argv) {
            for (size_t j = 0; j < cmd->argc; ++j) {
                free(cmd->argv[j]);
            }
            free(cmd->argv);
        }
        if (cmd->redirs) {
            for (size_t j = 0; j < cmd->redir_count; ++j) {
                free(cmd->redirs[j].target);
            }
            free(cmd->redirs);
        }
    }
    free(pipeline->commands);
    pipeline->commands = NULL;
    pipeline->length = 0u;
    pipeline->background = false;
    pipeline->terminator = false;
}
References gs_simple_command::argc, gs_simple_command::argv, gs_pipeline::background, gs_pipeline::commands, gs_pipeline::length, gs_simple_command::redir_count, gs_simple_command::redirs, gs_redirection::target, and gs_pipeline::terminator.
Referenced by run_line().
parse_io_number()
int parse_io_number (const char * text, int * out_fd) static
Definition at line 135 of file parser.c.
{
    errno = 0;
    char *end = NULL;
    long val = strtol(text, &end, 10);
    if (errno != 0 || !end || *end != '\0' || val < 0 || val > 9) {
        return GS_ERR_PARSE;
    }
    *out_fd = (int)val;
    return GS_OK;
}
References GS_ERR_PARSE, and GS_OK.
Referenced by parse_simple_command().
parse_redirection()
int parse_redirection (parse_state * st, gs_redirection_type type, int default_fd, int explicit_fd, gs_redirection * out_redir) static
Definition at line 146 of file parser.c.
{
    const gs_token *target_token = consume(st);
    if (!target_token || target_token->type != GS_TOKEN_WORD || !target_token->lexeme) {
        return GS_ERR_PARSE;
    }
    char *dup = strdup(target_token->lexeme);
    if (!dup) {
        return GS_ERR_ALLOC;
    }
    out_redir->fd = explicit_fd >= 0 ? explicit_fd : default_fd;
    out_redir->type = type;
    out_redir->target = dup;
    return GS_OK;
}
References consume(), gs_redirection::fd, GS_ERR_ALLOC, GS_ERR_PARSE, GS_OK, GS_TOKEN_WORD, gs_token::lexeme, gs_redirection::target, gs_redirection::type, and gs_token::type.
Referenced by parse_simple_command().
parse_simple_command()
int parse_simple_command (parse_state * st, gs_simple_command * out_cmd) static
Definition at line 161 of file parser.c.
{
    memset(out_cmd, 0, sizeof(*out_cmd));
    string_vec argv_vec = {0};
    redir_vec redirs = {0};
    int rc = GS_OK;
    while (true) {
        const gs_token *token = peek(st);
        if (!token) {
            rc = GS_ERR_PARSE;
            break;
        }
        if (token->type == GS_TOKEN_WORD) {
            char *dup = strdup(token->lexeme ? token->lexeme : "");
            if (!dup) {
                rc = GS_ERR_ALLOC;
                break;
            }
            rc = string_vec_push(&argv_vec, dup);
            if (rc != GS_OK) {
                free(dup);
                break;
            }
            (void)consume(st);
            continue;
        }
        if (token->type == GS_TOKEN_IO_NUMBER) {
            int fd = 0;
            rc = parse_io_number(token->lexeme, &fd);
            if (rc != GS_OK) {
                break;
            }
            (void)consume(st);
            const gs_token *op = peek(st);
            if (!op) {
                rc = GS_ERR_PARSE;
                break;
            }
            gs_redirection redir = {0};
            switch (op->type) {
            case GS_TOKEN_REDIR_IN:
                (void)consume(st);
                rc = parse_redirection(st, GS_REDIR_STDIN, 0, fd, &redir);
                break;
            case GS_TOKEN_REDIR_OUT:
                (void)consume(st);
                rc = parse_redirection(st, GS_REDIR_STDOUT, 1, fd, &redir);
                break;
            case GS_TOKEN_REDIR_APPEND:
                (void)consume(st);
                rc = parse_redirection(st, GS_REDIR_STDOUT_APPEND, 1, fd, &redir);
                break;
            default:
                rc = GS_ERR_PARSE;
                break;
            }
            if (rc != GS_OK) {
                break;
            }
            rc = redir_vec_push(&redirs, &redir);
            if (rc != GS_OK) {
                free(redir.target);
                break;
            }
            continue;
        }
        if (token->type == GS_TOKEN_REDIR_IN || token->type == GS_TOKEN_REDIR_OUT || token->type == GS_TOKEN_REDIR_APPEND) {
            gs_redirection redir = {0};
            gs_redirection_type rtype = GS_REDIR_STDOUT;
            int default_fd = 1;
            if (token->type == GS_TOKEN_REDIR_IN) {
                rtype = GS_REDIR_STDIN;
                default_fd = 0;
            } else if (token->type == GS_TOKEN_REDIR_APPEND) {
                rtype = GS_REDIR_STDOUT_APPEND;
                default_fd = 1;
            }
            (void)consume(st);
            rc = parse_redirection(st, rtype, default_fd, -1, &redir);
            if (rc != GS_OK) {
                break;
            }
            rc = redir_vec_push(&redirs, &redir);
            if (rc != GS_OK) {
                free(redir.target);
                break;
            }
            continue;
        }
        break;
    }
    if (rc != GS_OK) {
        string_vec_dispose(&argv_vec);
        redir_vec_dispose(&redirs);
        return rc;
    }
    if (argv_vec.length == 0u && redirs.length == 0u) {
        string_vec_dispose(&argv_vec);
        redir_vec_dispose(&redirs);
        return GS_ERR_PARSE;
    }
    rc = string_vec_push(&argv_vec, NULL);
    if (rc != GS_OK) {
        string_vec_dispose(&argv_vec);
        redir_vec_dispose(&redirs);
        return rc;
    }
    out_cmd->argc = argv_vec.length - 1u;
    out_cmd->argv = argv_vec.items;
    out_cmd->redirs = redirs.items;
    out_cmd->redir_count = redirs.length;
    return GS_OK;
}
References gs_simple_command::argc, gs_simple_command::argv, consume(), GS_ERR_ALLOC, GS_ERR_PARSE, GS_OK, GS_REDIR_STDIN, GS_REDIR_STDOUT, GS_REDIR_STDOUT_APPEND, GS_TOKEN_IO_NUMBER, GS_TOKEN_REDIR_APPEND, GS_TOKEN_REDIR_IN, GS_TOKEN_REDIR_OUT, GS_TOKEN_WORD, gs_token::lexeme, parse_io_number(), parse_redirection(), peek(), gs_simple_command::redir_count, redir_vec_dispose(), redir_vec_push(), gs_simple_command::redirs, string_vec_dispose(), string_vec_push(), gs_redirection::target, and gs_token::type.
Referenced by gs_parse_tokens().
peek()
const gs_token * peek (const parse_state * st) static
Definition at line 12 of file parser.c.
{
    if (st->index >= st->tokens->length) {
        return NULL;
    }
    return &st->tokens->items[st->index];
}
References gs_token_buffer::items, and gs_token_buffer::length.
Referenced by consume(), gs_parse_tokens(), and parse_simple_command().
redir_vec_dispose()
void redir_vec_dispose (redir_vec * vec) static
Definition at line 73 of file parser.c.
{
    if (!vec) {
        return;
    }
    for (size_t i = 0; i < vec->length; ++i) {
        free(vec->items[i].target);
    }
    free(vec->items);
    vec->items = NULL;
    vec->length = 0u;
    vec->capacity = 0u;
}
References gs_redirection::target.
Referenced by parse_simple_command().
redir_vec_push()
int redir_vec_push (redir_vec * vec, const gs_redirection * redir) static
Definition at line 86 of file parser.c.
{
    if (vec->length + 1u > vec->capacity) {
        size_t new_cap = vec->capacity ? vec->capacity * 2u : 2u;
        gs_redirection *tmp = (gs_redirection *)realloc(vec->items, new_cap * sizeof(gs_redirection));
        if (!tmp) {
            return GS_ERR_ALLOC;
        }
        vec->items = tmp;
        vec->capacity = new_cap;
    }
    vec->items[vec->length++] = *redir;
    return GS_OK;
}
References GS_ERR_ALLOC, and GS_OK.
Referenced by parse_simple_command().
string_vec_dispose()
void string_vec_dispose (string_vec * vec) static
Definition at line 46 of file parser.c.
{
    if (!vec) {
        return;
    }
    for (size_t i = 0; i < vec->length; ++i) {
        free(vec->items[i]);
    }
    free(vec->items);
    vec->items = NULL;
    vec->length = 0u;
    vec->capacity = 0u;
}
Referenced by parse_simple_command().
string_vec_push()
int string_vec_push (string_vec * vec, char * value) static
Definition at line 59 of file parser.c.
{
    if (vec->length + 1u > vec->capacity) {
        size_t new_cap = vec->capacity ? vec->capacity * 2u : 4u;
        char **tmp = (char **)realloc(vec->items, new_cap * sizeof(char *));
        if (!tmp) {
            return GS_ERR_ALLOC;
        }
        vec->items = tmp;
        vec->capacity = new_cap;
    }
    vec->items[vec->length++] = value;
    return GS_OK;
}
References GS_ERR_ALLOC, and GS_OK.
Referenced by parse_simple_command().