GenShell: registry.c File Reference
registry.c File Reference
#include "builtin.h"
#include <stdlib.h>
#include <string.h>
Functions
static int builtin_cd (struct gs_shell *shell, int argc, char *const argv[])
static int builtin_exit (struct gs_shell *shell, int argc, char *const argv[])
static int builtin_pwd (struct gs_shell *shell, int argc, char *const argv[])
static int builtin_echo (struct gs_shell *shell, int argc, char *const argv[])
static int builtin_export (struct gs_shell *shell, int argc, char *const argv[])
static int builtin_unset (struct gs_shell *shell, int argc, char *const argv[])
static int builtin_umask (struct gs_shell *shell, int argc, char *const argv[])
static int compare_builtin (const void *lhs, const void *rhs)
const gs_builtin_spec * gs_builtin_lookup (const char *name)
int genshell_builtin_cd (struct gs_shell *, int, char *const [])
int genshell_builtin_exit (struct gs_shell *, int, char *const [])
int genshell_builtin_pwd (struct gs_shell *, int, char *const [])
int genshell_builtin_echo (struct gs_shell *, int, char *const [])
int genshell_builtin_export (struct gs_shell *, int, char *const [])
int genshell_builtin_unset (struct gs_shell *, int, char *const [])
int genshell_builtin_umask (struct gs_shell *, int, char *const [])
Variables
static const gs_builtin_spec k_builtins []
Function Documentation
builtin_cd()
int builtin_cd (struct gs_shell * shell, int argc, char *const argv[]) static
Definition at line 53 of file registry.c.
{
    return genshell_builtin_cd(shell, argc, argv);
}
References genshell_builtin_cd().
builtin_echo()
int builtin_echo (struct gs_shell * shell, int argc, char *const argv[]) static
Definition at line 65 of file registry.c.
{
    return genshell_builtin_echo(shell, argc, argv);
}
References genshell_builtin_echo().
builtin_exit()
int builtin_exit (struct gs_shell * shell, int argc, char *const argv[]) static
Definition at line 57 of file registry.c.
{
    return genshell_builtin_exit(shell, argc, argv);
}
References genshell_builtin_exit().
builtin_export()
int builtin_export (struct gs_shell * shell, int argc, char *const argv[]) static
Definition at line 69 of file registry.c.
{
    return genshell_builtin_export(shell, argc, argv);
}
References genshell_builtin_export().
builtin_pwd()
int builtin_pwd (struct gs_shell * shell, int argc, char *const argv[]) static
Definition at line 61 of file registry.c.
{
    return genshell_builtin_pwd(shell, argc, argv);
}
References genshell_builtin_pwd().
builtin_umask()
int builtin_umask (struct gs_shell * shell, int argc, char *const argv[]) static
Definition at line 77 of file registry.c.
{
    return genshell_builtin_umask(shell, argc, argv);
}
References genshell_builtin_umask().
builtin_unset()
int builtin_unset (struct gs_shell * shell, int argc, char *const argv[]) static
Definition at line 73 of file registry.c.
{
    return genshell_builtin_unset(shell, argc, argv);
}
References genshell_builtin_unset().
compare_builtin()
int compare_builtin (const void * lhs, const void * rhs) static
Definition at line 24 of file registry.c.
{
    const gs_builtin_spec *a = (const gs_builtin_spec *)lhs;
    const gs_builtin_spec *b = (const gs_builtin_spec *)rhs;
    return strcmp(a->name, b->name);
}
References gs_builtin_spec::name.
Referenced by gs_builtin_lookup().
genshell_builtin_cd()
int genshell_builtin_cd (struct gs_shell * shell, int argc, char * const argv[]) extern
Definition at line 19 of file cd.c.
{
    (void)shell;
    const char *target = NULL;
    int status = 0;
    char old_pwd[PATH_MAX];
    bool have_old = false;
    if (getcwd(old_pwd, sizeof(old_pwd)) != NULL) {
        have_old = true;
    }
    if (argc < 2) {
        target = getenv("HOME");
        if (!target || target[0] == '\0') {
            fprintf(stderr, "genshell: cd: HOME not set\n");
            return 1;
        }
    } else if (argc > 2) {
        fprintf(stderr, "genshell: cd: too many arguments\n");
        return 1;
    } else if (strcmp(argv[1], "-") == 0) {
        target = getenv("OLDPWD");
        if (!target || target[0] == '\0') {
            fprintf(stderr, "genshell: cd: OLDPWD not set\n");
            return 1;
        }
    } else {
        target = argv[1];
    }
    if (chdir(target) != 0) {
        fprintf(stderr, "genshell: cd: %s: %s\n", target, strerror(errno));
        return 1;
    }
    char new_pwd[PATH_MAX];
    if (getcwd(new_pwd, sizeof(new_pwd)) == NULL) {
        /* Fall back to the target path if getcwd fails (e.g., perms issues). */
        strncpy(new_pwd, target, sizeof(new_pwd) - 1u);
        new_pwd[sizeof(new_pwd) - 1u] = '\0';
    }
    if (have_old) {
        setenv("OLDPWD", old_pwd, 1);
    }
    setenv("PWD", new_pwd, 1);
    if (argc == 2 && strcmp(argv[1], "-") == 0) {
        printf("%s\n", new_pwd);
        fflush(stdout);
    }
    return status;
}
Referenced by builtin_cd().
genshell_builtin_echo()
int genshell_builtin_echo (struct gs_shell * shell, int argc, char * const argv[]) extern
Definition at line 14 of file echo.c.
{
    (void)shell;
    int start = 1;
    bool newline = true;
    if (argc > 1 && strcmp(argv[1], "-n") == 0) {
        newline = false;
        start = 2;
    }
    for (int i = start; i < argc; ++i) {
        fputs(argv[i], stdout);
        if (i + 1 < argc) {
            fputc(' ', stdout);
        }
    }
    if (newline) {
        fputc('\n', stdout);
    }
    fflush(stdout);
    return 0;
}
Referenced by builtin_echo().
genshell_builtin_exit()
int genshell_builtin_exit (struct gs_shell * shell, int argc, char * const argv[]) extern
Definition at line 16 of file exit.c.
{
    if (!shell) {
        return GS_ERR_EXEC;
    }
    if (argc > 2) {
        fprintf(stderr, "genshell: exit: too many arguments\n");
        return 1;
    }
    int exit_code = shell->last_status;
    if (argc == 2) {
        errno = 0;
        char *end = NULL;
        long value = strtol(argv[1], &end, 10);
        if (errno != 0 || !end || *end != '\0') {
            fprintf(stderr, "genshell: exit: %s: numeric argument required\n", argv[1]);
            shell->exit_requested = true;
            shell->exit_status = 2;
            return 2;
        }
        exit_code = (int)(value & 0xFF);
    }
    shell->exit_requested = true;
    shell->exit_status = exit_code;
    return exit_code;
}
References gs_shell::exit_requested, gs_shell::exit_status, GS_ERR_EXEC, and gs_shell::last_status.
Referenced by builtin_exit().
genshell_builtin_export()
int genshell_builtin_export (struct gs_shell * shell, int argc, char * const argv[]) extern
Definition at line 45 of file export.c.
{
    (void)shell;
    if (argc == 1) {
        print_exports();
        return 0;
    }
    int status = 0;
    for (int i = 1; i < argc; ++i) {
        const char *arg = argv[i];
        const char *eq = strchr(arg, '=');
        if (eq) {
            size_t name_len = (size_t)(eq - arg);
            char *name = strndup(arg, name_len);
            if (!name) {
                fprintf(stderr, "genshell: export: allocation failure\n");
                return 1;
            }
            if (!is_valid_name(name)) {
                fprintf(stderr, "genshell: export: `%s': invalid identifier\n", arg);
                free(name);
                status = 1;
                continue;
            }
            const char *value = eq + 1;
            if (setenv(name, value, 1) != 0) {
                fprintf(stderr, "genshell: export: failed to set %s\n", name);
                status = 1;
            }
            free(name);
        } else {
            if (!is_valid_name(arg)) {
                fprintf(stderr, "genshell: export: `%s': invalid identifier\n", arg);
                status = 1;
                continue;
            }
            const char *value = getenv(arg);
            if (!value) {
                value = "";
            }
            if (setenv(arg, value, 1) != 0) {
                fprintf(stderr, "genshell: export: failed to export %s\n", arg);
                status = 1;
            }
        }
    }
    return status;
}
References is_valid_name(), and print_exports().
Referenced by builtin_export().
genshell_builtin_pwd()
int genshell_builtin_pwd (struct gs_shell * shell, int argc, char * const argv[]) extern
Definition at line 17 of file pwd.c.
{
    (void)shell;
    bool logical = true;
    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "-L") == 0) {
            logical = true;
        } else if (strcmp(argv[i], "-P") == 0) {
            logical = false;
        } else {
            fprintf(stderr, "genshell: pwd: invalid option -- %s\n", argv[i]);
            return 1;
        }
    }
    const char *pwd = NULL;
    char buf[PATH_MAX];
    if (logical) {
        pwd = getenv("PWD");
    }
    if (!pwd || pwd[0] == '\0' || !logical) {
        if (getcwd(buf, sizeof(buf)) == NULL) {
            fprintf(stderr, "genshell: pwd: %s\n", strerror(errno));
            return 1;
        }
        pwd = buf;
    }
    printf("%s\n", pwd);
    fflush(stdout);
    return 0;
}
Referenced by builtin_pwd().
genshell_builtin_umask()
int genshell_builtin_umask (struct gs_shell * shell, int argc, char * const argv[]) extern
Definition at line 42 of file umask.c.
{
    (void)shell;
    int argi = 1;
    int symbolic = 0;
    if (argc > 1 && strcmp(argv[1], "-S") == 0) {
        symbolic = 1;
        argi = 2;
    }
    if (argc == argi) {
        mode_t mask = umask(0);
        umask(mask);
        if (symbolic) {
            print_symbolic(mask);
        } else {
            print_octal(mask);
        }
        return 0;
    }
    if (argc > argi + 1) {
        fprintf(stderr, "genshell: umask: too many arguments\n");
        return 1;
    }
    const char *arg = argv[argi];
    errno = 0;
    char *end = NULL;
    long value = strtol(arg, &end, 8);
    if (errno != 0 || !end || *end != '\0' || value < 0 || value > 0777) {
        fprintf(stderr, "genshell: umask: invalid mode: %s\n", arg);
        return 1;
    }
    umask((mode_t)value);
    return 0;
}
References print_octal(), and print_symbolic().
Referenced by builtin_umask().
genshell_builtin_unset()
int genshell_builtin_unset (struct gs_shell * shell, int argc, char * const argv[]) extern
Definition at line 29 of file unset.c.
{
    (void)shell;
    if (argc < 2) {
        return 0;
    }
    int status = 0;
    for (int i = 1; i < argc; ++i) {
        if (!is_valid_name(argv[i])) {
            fprintf(stderr, "genshell: unset: `%s': invalid identifier\n", argv[i]);
            status = 1;
            continue;
        }
        if (unsetenv(argv[i]) != 0) {
            fprintf(stderr, "genshell: unset: failed to unset %s\n", argv[i]);
            status = 1;
        }
    }
    return status;
}
References is_valid_name().
Referenced by builtin_unset().
gs_builtin_lookup()
const gs_builtin_spec * gs_builtin_lookup (const char * name)
Definition at line 30 of file registry.c.
{
    if (!name) {
        return NULL;
    }
    gs_builtin_spec key = {name, NULL, 0u};
    const gs_builtin_spec *result = (const gs_builtin_spec *)bsearch(
        &key,
        k_builtins,
        sizeof(k_builtins) / sizeof(k_builtins[0]),
        sizeof(k_builtins[0]),
        compare_builtin);
    return result;
}
References compare_builtin(), and k_builtins.
Referenced by prepare_command().
Variable Documentation
k_builtins
const gs_builtin_spec k_builtins[] static
Initial value:
= {
    {"cd", builtin_cd, GS_BUILTIN_FLAG_PARENT | GS_BUILTIN_FLAG_SPECIAL},
    {"echo", builtin_echo, 0u},
    {"exit", builtin_exit, GS_BUILTIN_FLAG_PARENT | GS_BUILTIN_FLAG_SPECIAL},
    {"export", builtin_export, GS_BUILTIN_FLAG_PARENT | GS_BUILTIN_FLAG_SPECIAL},
    {"pwd", builtin_pwd, GS_BUILTIN_FLAG_PARENT},
    {"umask", builtin_umask, GS_BUILTIN_FLAG_PARENT | GS_BUILTIN_FLAG_SPECIAL},
    {"unset", builtin_unset, GS_BUILTIN_FLAG_PARENT | GS_BUILTIN_FLAG_SPECIAL},
}
Definition at line 14 of file registry.c.
{
    {"cd", builtin_cd, GS_BUILTIN_FLAG_PARENT | GS_BUILTIN_FLAG_SPECIAL},
    {"echo", builtin_echo, 0u},
    {"exit", builtin_exit, GS_BUILTIN_FLAG_PARENT | GS_BUILTIN_FLAG_SPECIAL},
    {"export", builtin_export, GS_BUILTIN_FLAG_PARENT | GS_BUILTIN_FLAG_SPECIAL},
    {"pwd", builtin_pwd, GS_BUILTIN_FLAG_PARENT},
    {"umask", builtin_umask, GS_BUILTIN_FLAG_PARENT | GS_BUILTIN_FLAG_SPECIAL},
    {"unset", builtin_unset, GS_BUILTIN_FLAG_PARENT | GS_BUILTIN_FLAG_SPECIAL},
};
Referenced by gs_builtin_lookup().